# CMake generated Testfile for 
# Source directory: /Users/andrzejmarczewski/Documents/GitHub/VxStudio
# Build directory: /Users/andrzejmarczewski/Documents/GitHub/VxStudio
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("VxTuneAnalysisTests" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VxTuneAnalysisTests")
set_tests_properties("VxTuneAnalysisTests" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1058;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VxTuneRendererTests" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VxTuneRendererTests")
set_tests_properties("VxTuneRendererTests" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1070;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VxTunePluginTests" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VxTunePluginTests")
set_tests_properties("VxTunePluginTests" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1091;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXDeverbTests" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXDeverbTests")
set_tests_properties("VXDeverbTests" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1142;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXDeverbMeasure" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXDeverbMeasure")
set_tests_properties("VXDeverbMeasure" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1158;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXLevelerMeasure" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXLevelerMeasure")
set_tests_properties("VXLevelerMeasure" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1176;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXLevelerTuneSearch" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXLevelerTuneSearch")
set_tests_properties("VXLevelerTuneSearch" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1194;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VxLevelerRiderTests" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VxLevelerRiderTests")
set_tests_properties("VxLevelerRiderTests" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1212;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXRebalanceMeasure" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXRebalanceMeasure")
set_tests_properties("VXRebalanceMeasure" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1228;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VxStudioVoiceAnalysisTests" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VxStudioVoiceAnalysisTests")
set_tests_properties("VxStudioVoiceAnalysisTests" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1281;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXStudioPluginRegressionTests" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXStudioPluginRegressionTests")
set_tests_properties("VXStudioPluginRegressionTests" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1347;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXStudioAnalyserTests" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXStudioAnalyserTests")
set_tests_properties("VXStudioAnalyserTests" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1366;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXRepairPassthroughCheck" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXRepairPassthroughCheck")
set_tests_properties("VXRepairPassthroughCheck" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1394;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXWidthShellCheck" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXWidthShellCheck")
set_tests_properties("VXWidthShellCheck" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1407;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXStudioBatchAudioCheck" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXStudioBatchAudioCheck")
set_tests_properties("VXStudioBatchAudioCheck" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1459;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
add_test("VXSuiteProfile" "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/VXSuiteProfile")
set_tests_properties("VXSuiteProfile" PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/andrzejmarczewski/Documents/GitHub/VxStudio/cmake/VxStudioValidation.cmake;10;add_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;1527;vxstudio_add_executable_test;/Users/andrzejmarczewski/Documents/GitHub/VxStudio/CMakeLists.txt;0;")
subdirs("JUCE")
subdirs("Source/vxstudio/tools/test_host")
